# Generated by Django 4.2.1 on 2023-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('posts', '0003_alter_comment_content_alter_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boardAnimalTypes',
            field=models.ManyToManyField(null=True, related_name='posts', to='pets.pet'),
        ),
    ]
