# Generated by Django 4.2 on 2023-05-14 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용중인 이메일 입니다.'}, max_length=255, unique=True, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': '이미 사용중인 닉네임 입니다.'}, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, '닉네임은 2자 이상이어야합니다.')], verbose_name='username'),
        ),
    ]
