version: '3'

services:  
  web:
    container_name: web
    build: .
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/app/static
      # - logs_volume:/code/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
    networks:
      - elastic

  elasticsearch:
  
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
  
  nginx:
   
    container_name: nginx
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
      - static_volume:/code/app/static
    ports:
      - 80:80
    depends_on:
      - web 
    networks:
      - elastic 

  kibana:

    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    volumes:
      - .docker/kibana/kibana.yml:/usr/share/kibana/kibana.yml
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge 
  
volumes:
  static_volume:
  kibana_data:



      

