version: '3'

services:  
  web:
    container_name: web
    build: .
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/app/static
      # - logs_volume:/code/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
  
  nginx:
    # image: nginx:latest
    container_name: nginx
    restart: always
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
      - static_volume:/code/app/static
    ports:
      - 80:80
    depends_on:
      - web 
    networks:
      - elastic  

networks:
  elastic:
    driver: bridge 
  
volumes:
  static_volume:
#   elasticsearch_volume:
  # logs_volume:

  
  # web -> command:  gunicorn --bind 0.0.0.0:8000 config.wsgi:application 
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  #   container_name: elasticsearch
  #   restart: always
  #   volumes:
  #     - elasticsearch_volume:/usr/share/elasticsearch/data--> Named Volume
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic

  # kibana:
  #   image: kibana:7.14.0
  #   container_name: kibana
  #   build:
  #     context: .docker/kibana
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #     - logstash
  #   networks:
  #     - elastic

  # filebeat:
  #   image: filebeat:7.14.0
  #   container_name: filebeat
  #   build: 
  #     context: .docker/filebeat
  #     dockerfile: Dockerfile
  #   volumes:
  #     - logs_volume:/code/app/logs
  #   command: filebeat -c /usr/share/filebeat/filebeat.yml -e -d "*" -strict.perms=false
  #   depends_on:
  #     - web
    # networks:
    #   - elastic

  # logstash:
  #   image: logstash:7.14.0
  #   container_name: logstash
  #   restart: always
  #   build:
  #     context: .docker/logstash
  #     dockerfile: Dockerfile
  #   volumes:
  #     - logs_volume:/code/app/logs:ro
  #   # volumes:
  #   #   - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   command: logstash -f /usr/share/logstash/pipeline/logstash.conf
  #   depends_on:
  #     - elasticsearch
    # networks:
    #   - elastic    

      

